//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clientWSUser.wsUser {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsUser.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCountPersonas", ReplyAction="http://tempuri.org/IService1/getCountPersonasResponse")]
        long getCountPersonas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCountPersonas", ReplyAction="http://tempuri.org/IService1/getCountPersonasResponse")]
        System.Threading.Tasks.Task<long> getCountPersonasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getApellidoPersona", ReplyAction="http://tempuri.org/IService1/getApellidoPersonaResponse")]
        string getApellidoPersona(string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getApellidoPersona", ReplyAction="http://tempuri.org/IService1/getApellidoPersonaResponse")]
        System.Threading.Tasks.Task<string> getApellidoPersonaAsync(string documento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : clientWSUser.wsUser.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<clientWSUser.wsUser.IService1>, clientWSUser.wsUser.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public long getCountPersonas() {
            return base.Channel.getCountPersonas();
        }
        
        public System.Threading.Tasks.Task<long> getCountPersonasAsync() {
            return base.Channel.getCountPersonasAsync();
        }
        
        public string getApellidoPersona(string documento) {
            return base.Channel.getApellidoPersona(documento);
        }
        
        public System.Threading.Tasks.Task<string> getApellidoPersonaAsync(string documento) {
            return base.Channel.getApellidoPersonaAsync(documento);
        }
    }
}
